#!/bin/sh -eu
MACHINE=$1
TARGET=$2

SIZE=${SIZE:-4G}
FS=${FS:-ext4}

VG=$(lvs --noheadings | awk "/^  $MACHINE /{print \$2}")
if [ -z "$VG" ]; then
	VG=$(vgs --noheadings | awk '/^  vg-/{print $1}')
	if [ -z "$VG" ]; then
		# persistent storage not found, keep it all in RAM
		exit 0
	fi
	lvcreate -L $SIZE $VG -n $MACHINE
	mkfs.$FS /dev/$VG/$MACHINE
fi

mount /dev/$VG/$MACHINE /var/lib/machines/$MACHINE/$TARGET
