#!/bin/sh -eu
. /etc/default/barley-seed
IP=$(ip address show dev br0 | awk '/inet / {print $2}' | grep -v '^169.254' | head -1 | cut -d/ -f1)
SSH="$(cat /etc/ssh/ssh_host_ed25519_key.pub)"
cd /var/lib/barley

cat > machine.conf <<EOF
dn=cn=$(hostname)
signing_key
tls_www_client
tls_www_server
EOF
certtool --generate-request --no-text --load-privkey machine.key --outfile machine.csr --template machine.conf
rm machine.conf
CSR=$(LANG=C perl -pe 's/\n/\\n/' < machine.csr)

curl -s -o certs.json \
     -d '{"otp":"'"$OTP"'","ip":"'"$IP"'","ssh":"'"$SSH"'","csr":"'"$CSR"'"}' \
     -H 'Content-Type: application/json' \
     http://"$SOWER":8000/register/$(hostname)

install -d -m 700 /root/.ssh
cat certs.json | jq -r .admin > /root/.ssh/authorized_keys
cat certs.json | jq -r .host > /etc/ssh/ssh_host_ed25519_key-cert.pub
cat certs.json | jq -r .ca  > ca.crt
cat certs.json | jq -r .cert > machine.crt
cat ca.crt >> machine.crt
rm certs.json
