[package]
name = "barley"
version = "0.1.0"
authors = ["Dmitry Borodaenko <angdraug@debian.org>"]
edition = "2018"

[dependencies]
actix-files = "0.3"
actix-web = "3"
env_logger = "0.8"
rand = "0.7"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
