#!/bin/sh -eux

/usr/sbin/iucode_tool --write-earlyfw=$MACHINE.cpio.zst --overwrite /lib/firmware/intel-ucode

(cd /var/lib/machines/$MACHINE && find . -path ./boot -prune -o -print ) | \
  LC_ALL=C sort | \
  systemd-nspawn -M $MACHINE -UPq /bin/cpio --quiet --reproducible -o -H newc | \
  zstd >> $MACHINE.cpio.zst

cp /var/lib/machines/$MACHINE/boot/vmlinuz-* $MACHINE.vmlinuz
