#!/bin/sh -eu
. /etc/default/barley-seed
IP=$(ip address show dev br0 | awk '/inet / {print $2}' | grep -v '^169.254' | head -1 | cut -d/ -f1)
SSH="$(cat /etc/ssh/ssh_host_ed25519_key.pub)"
curl -s -o /etc/ssh/ssh_host_ed25519_key-cert.pub \
	-d '{"otp":"'"$OTP"'","ip":"'"$IP"'","ssh":"'"$SSH"'"}' \
	-H 'Content-Type: application/json' \
	http://"$SOWER":8000/register/$(hostname)
