#!/bin/sh
ADDRESS=$(networkctl status -n0 --no-pager | awk '/Address:/{print $2}')
sed -i -e "s/^dhcp-range=.*$/dhcp-range=$ADDRESS,proxy/" \
	-e "s|//[0-9.]*/|//$ADDRESS/|" \
	/etc/dnsmasq.d/sower.conf
